config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :plants

  root 'static_pages#home'

  get 'about', to: 'static_pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :plants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @plants = current_user.plants
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def new
    @plant = Plant.new
  end

  def edit
  end

  def create
    @plant = current_user.plants.build(plant_params)

    @plant.save
    redirect_to @plant
  end

  def update
  end

  def destroy
  end

  private
  def plant_params
    params.require(:plant).permit(:common_name, :scientific_name,
                                  :nickname, :origin, :watering_schedule,
                                  :light_requirement, :image
                                 )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
    @seedling = ":seedling:"
    @sparkling_heart = ":sparkling_heart:"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content, **options)
    Twemoji.parse(h(content), options).html_safe if content.present?
  end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class=navbar-header">
      <%= link_to "Maceta", root_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Plant", new_plant_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Garden", plants_path %></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maceta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/plants/create.html.erb
<h1>Plants#create</h1>
<p>Find me in app/views/plants/create.html.erb</p>

app/views/plants/destroy.html.erb
<h1>Plants#destroy</h1>
<p>Find me in app/views/plants/destroy.html.erb</p>

app/views/plants/edit.html.erb
<h1>Plants#edit</h1>
<p>Find me in app/views/plants/edit.html.erb</p>

app/views/plants/index.html.erb
<div class="jumbotron plant-facts">
  <h2 class="text-center">My Garden</h2>
  <% @plants.each do |plant| %>
    <div class="row center">
      <% unless plant.image.blank? %>
        <%= image_tag plant.image.display.url %>
      <% end %>
    </div>
    <br />
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Common Name:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= plant.common_name %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Scientific Name:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= plant.scientific_name %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Nickname:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= plant.nickname %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Origin:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= plant.origin %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Watering Schedule:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= plant.watering_schedule %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Light Requirement:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= plant.light_requirement %>
      </div>
    </div>
  <% end %>
</div>

app/views/plants/new.html.erb
<div class="center jumbotron">
  <h2>New Plant</h2>
  <%= form_for @plant, class:"plant-form" do |f|%>
    <div class="row">
      <div class="row form-group">
        <%= f.label :common_name, class: "col-sm-6 text-left" %>
        <div class="col-sm-6">
          <%= f.text_field :common_name, class: "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :scientific_name, class: "col-sm-6 text-left" %>
        <div class="col-sm-6">
          <%= f.text_field :scientific_name, class: "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :nickname, class: "col-sm-6 text-left" %>
        <div class="col-sm-6">
          <%= f.text_field :nickname, class: "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :origin, class: "col-sm-6 text-left" %>
        <div class="col-sm-6">
          <%= f.text_field :origin, class: "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :watering_schedule, class: "col-sm-6 text-left" %>
        <div class="col-sm-6">
          <%= f.select :watering_schedule, ["Weekly", "Bi-Weekly", "Monthly", "Sparse"], {}, { class: "form-control" } %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :light_requirement, class: "col-sm-6 text-left" %>
        <div class="col-sm-6">
          <%= f.select :light_requirement, ["Direct Sunlight", "Indirect Sunlight", "Shady/Dark"], {}, { class: "form-control" } %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :image, class: "col-sm-6 text-left" %>
        <div class="col-sm-6">
          <%= f.file_field :image, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row form-group">
      <%= f.submit class: "btn btn-plum" %>
    </div>
  <% end %>
</div>

app/views/plants/show.html.erb
<div class="container">
  <div class="jumbotron plant-facts">
    <div class="row center">
      <% unless @plant.image.blank? %>
        <%= image_tag @plant.image.display.url %>
      <% end %>
    </div>
    <br />
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Common Name:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= @plant.common_name %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Scientific Name:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= @plant.scientific_name %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Nickname:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= @plant.nickname %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Origin:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= @plant.origin %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Watering Schedule:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= @plant.watering_schedule %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <strong class="plant-info">Light Requirement:</strong>
      </div>
      <div class="col-sm-6 plant-data">
        <%= @plant.light_requirement %>
      </div>
    </div>
  </div>
</div>

app/views/plants/update.html.erb
<h1>Plants#update</h1>
<p>Find me in app/views/plants/update.html.erb</p>

app/views/static_pages/about.html.erb
<div class="center jumbotron">
  <h2>Maceta is a tool to help track your plants!</h2>

  <div class="row">
    <h3>With this tool, you will be able to:</h3>
    <ul class="feature-list list-unstyled">
      <li>
        <%= emojify @seedling %> Organize by scientific and common names.
      </li>
      <li>
        <%= emojify @seedling %> Keep a log of your plants' progress, milestones, and issues.
      </li>
      <li>
        <%= emojify @seedling %> Upload pictures of your plants.
      </li>
      <li>
        <%= emojify @seedling %> Set watering schedules and get notifications when it's time to water.
      </li>
      <li>
        <%= emojify @seedling %> Give your plants cute nicknames for easy reference<%= emojify @sparkling_heart %>.
      </li>
    </ul>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Maceta</h1>
  <h2>A plant tracking app</h2>
</div>